import { ConsoleLogLevel } from '../resolvers/types/generated.js';

export const data: {
    [id: string]: {
        __typename: 'ConsoleLogEvent',
        id: string,
        at: Date,
        message: string,
        logLevel: ConsoleLogLevel,
        testExecutionId: string,
    }
} = {
    '1': {
        __typename: 'ConsoleLogEvent',
        id: '1',
        at: new Date(1676903334127),
        message: 'Arguments: SENTRY WAS __NOT__ INITIALIZED. Logs will be forwarded to console instead.',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '2': {
        __typename: 'ConsoleLogEvent',
        id: '2',
        at: new Date(1676903334127),
        message: 'Arguments: SENTRY WAS __NOT__ INITIALIZED. Logs will be forwarded to console instead.',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '3': {
        __typename: 'ConsoleLogEvent',
        id: '3',
        at: new Date(1676903334339),
        message: 'Arguments: yui: NOT loaded: squarespace-cldr_resource_pack',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '4': {
        __typename: 'ConsoleLogEvent',
        id: '4',
        at: new Date(1676903334343),
        message: 'Arguments: yui: NOT loaded: squarespace-common_vendors_stable',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '5': {
        __typename: 'ConsoleLogEvent',
        id: '5',
        at: new Date(1676903334344),
        message: 'Arguments: yui: NOT loaded: squarespace-common_vendors',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '6': {
        __typename: 'ConsoleLogEvent',
        id: '6',
        at: new Date(1676903334359),
        message: 'Arguments: yui: NOT loaded: squarespace-performance',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '7': {
        __typename: 'ConsoleLogEvent',
        id: '7',
        at: new Date(1676903334339),
        message: 'Arguments: yui: NOT loaded: squarespace-cldr_resource_pack',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '8': {
        __typename: 'ConsoleLogEvent',
        id: '8',
        at: new Date(1676903334343),
        message: 'Arguments: yui: NOT loaded: squarespace-common_vendors_stable',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '9': {
        __typename: 'ConsoleLogEvent',
        id: '9',
        at: new Date(1676903334344),
        message: 'Arguments: yui: NOT loaded: squarespace-common_vendors',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '10': {
        __typename: 'ConsoleLogEvent',
        id: '10',
        at: new Date(1676903334359),
        message: 'Arguments: yui: NOT loaded: squarespace-performance',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '11': {
        __typename: 'ConsoleLogEvent',
        id: '11',
        at: new Date(1676903336396),
        message: 'Arguments: SENTRY WAS __NOT__ INITIALIZED. Logs will be forwarded to console instead.',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '12': {
        __typename: 'ConsoleLogEvent',
        id: '12',
        at: new Date(1676903336396),
        message: 'Arguments: SENTRY WAS __NOT__ INITIALIZED. Logs will be forwarded to console instead.',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '13': {
        __typename: 'ConsoleLogEvent',
        id: '13',
        at: new Date(1676903336580),
        message: 'Arguments: yui: NOT loaded: squarespace-cldr_resource_pack',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '14': {
        __typename: 'ConsoleLogEvent',
        id: '14',
        at: new Date(1676903336580),
        message: 'Arguments: yui: NOT loaded: squarespace-cldr_resource_pack',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '15': {
        __typename: 'ConsoleLogEvent',
        id: '15',
        at: new Date(1676903336583),
        message: 'Arguments: yui: NOT loaded: squarespace-common_vendors_stable',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '16': {
        __typename: 'ConsoleLogEvent',
        id: '16',
        at: new Date(1676903336583),
        message: 'Arguments: yui: NOT loaded: squarespace-common_vendors',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '17': {
        __typename: 'ConsoleLogEvent',
        id: '17',
        at: new Date(1676903336583),
        message: 'Arguments: yui: NOT loaded: squarespace-common_vendors_stable',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '18': {
        __typename: 'ConsoleLogEvent',
        id: '18',
        at: new Date(1676903336583),
        message: 'Arguments: yui: NOT loaded: squarespace-common_vendors',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '19': {
        __typename: 'ConsoleLogEvent',
        id: '19',
        at: new Date(1676903336586),
        message: 'Arguments: yui: NOT loaded: squarespace-performance',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
    '20': {
        __typename: 'ConsoleLogEvent',
        id: '20',
        at: new Date(1676903336586),
        message: 'Arguments: yui: NOT loaded: squarespace-performance',
        logLevel: ConsoleLogLevel.Warn,
        testExecutionId: '1234',
    },
}

export class ConsoleEvent {
    getById(id: string) {
        return data[id] ?? null;
    }
}
