name: Deploy
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build and Push to ECR
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      - name: Push
        env:
          ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY }}
        run: |
          docker build -t $ECR_REPOSITORY:$GITHUB_SHA .
          docker push $ECR_REPOSITORY:$GITHUB_SHA
          echo "::set-output name=image::$ECR_REPOSITORY:$GITHUB_SHA"

  deploy:
    name: Deploy to Lambda
    needs: build
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-2

      - name: Deploy
        env:
          ECR_REPOSITORY: ${{ vars.AWS_ECR_REPOSITORY }}
          LAMBDA_ARN: ${{ vars.AWS_LAMBDA_ARN }}
        run: |
          aws lambda update-function-code --function-name $LAMBDA_ARN --image-uri $ECR_REPOSITORY:$GITHUB_SHA
