name: Increment version and create release

on: 
  workflow_dispatch:
    inputs:
      version:
        description: 'New version number'  
        required: true

jobs:
  version_bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.TESTERLOOP_ACCESS_TOKEN }}
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Configure Git
        uses: fregante/setup-git-user@v2
      - name: Update package version
        run: npm version ${{ github.event.inputs.version }}
      - name: Push changes
        run: git push --follow-tags origin ${{ github.ref }}
      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.TESTERLOOP_ACCESS_TOKEN }}
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.TESTERLOOP_ACCESS_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          release_name: ${{ github.event.inputs.version }}
          body: ${{ steps.github_release.outputs.changelog }}
          